// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Tao Jin

#include "volumetric_kit/gfx/pipelines/hybrid_mesh_pipeline.hpp"

#include <cstddef>
#include <cstdint>
#include <utility>
#include <variant>

#include <glm/geometric.hpp>
#include <glm/vec3.hpp>

#include "volumetric_kit/core/vulkan/device.hpp"
#include "volumetric_kit/gfx/assets/mesh.hpp"
#include "volumetric_kit/gfx/core/device_requirements.hpp"
#include "volumetric_kit/gfx/core/shader.hpp"
#include "volumetric_kit/gfx/core/texture_upload.hpp"
#include "volumetric_kit/gfx/pipelines/gpu_mesh.hpp"
#include "volumetric_kit/gfx/pipelines/impl/pipeline_util.hpp"
#include "volumetric_kit/gfx/pipelines/live_mesh.hpp"

// Generated by vkc_embed_shaders from shaders/hybrid_mesh.{vert,frag}: the
// SPIR-V the library ships, as `vg_hybrid_mesh_{vert,frag}_spv` (+ `_size`).
#include "hybrid_mesh_frag.spv.hpp"
#include "hybrid_mesh_vert.spv.hpp"

namespace volumetric_kit::gfx::pipelines {

namespace {

// Per-frame constants for hybrid_mesh.{vert,frag}, shared by both stages. The
// light direction is a plain float[3] rather than a glm::vec3, so no glm
// alignment setting can pad it: `flags` then lands in the vec3's trailing four
// bytes, exactly where the shaders' std430 push block puts it, and the block
// stays 80 B.
struct PushConstants {
  glm::mat4 view_proj;  // projection * view (vertices are already world-space)
  float light_dir[3];   // world-space direction to the light (unit)
  uint32_t flags;       // HybridMeshFlags, passed through as the caller set it
};
static_assert(sizeof(PushConstants) == 80,
              "PushConstants must match the shader push block "
              "(mat4 + vec3 + uint)");
static_assert(offsetof(PushConstants, light_dir) == 64,
              "PushConstants layout drift");
static_assert(offsetof(PushConstants, flags) == 76,
              "PushConstants layout drift");

// hybrid_mesh.frag's specialization constants, constant_ids 0..3 in order. The
// flag bits it tests come from HybridMeshFlags here, so the enum is their one
// definition (the shader's defaults are 0, which switches a mode off); the
// sRGB bit tells the normal view to pre-decode its encoding so that a target
// which encodes on write stores the encoding itself.
struct FragmentSpecialization {
  uint32_t flag_lit;
  uint32_t flag_normals;
  VkBool32 srgb_target;
  uint32_t flag_vertex_color;
};

// The vertex ABI, pinned. A LiveMesh's vertices are written by a *separate
// process* (the reconstruction library, in its own repo) against these exact
// bytes, so reordering or resizing assets::Vertex is a silent wire break in
// both directions: a producer packing a different layout renders garbage, and
// an already-shipped producer breaks the moment this struct moves. Neither
// shows up as a validation error -- the stride still matches -- so the drift is
// caught here, at compile time.
static_assert(sizeof(assets::Vertex) == 64, "assets::Vertex stride drift");
static_assert(offsetof(assets::Vertex, position) == 0, "vertex layout drift");
static_assert(offsetof(assets::Vertex, normal) == 12, "vertex layout drift");
static_assert(offsetof(assets::Vertex, tangent) == 24, "vertex layout drift");
static_assert(offsetof(assets::Vertex, uv0) == 40, "vertex layout drift");
static_assert(offsetof(assets::Vertex, color) == 48, "vertex layout drift");

// Records one draw's geometry. A visitor rather than a get_if chain: std::visit
// requires every alternative to be handled, so adding a geometry source to
// HybridMeshDraw is a compile error here instead of a draw that silently
// records nothing.
struct RecordGeometry {
  VkCommandBuffer cmd;

  // Static mesh: owns its buffers, index count fixed at upload. Skip an empty
  // or moved-from one rather than record against a stale binding.
  void operator()(const GpuMesh* mesh) const {
    if (mesh != nullptr && mesh->valid()) {
      mesh->record_draw(cmd);
    }
  }

  // Live mesh: borrowed buffers, GPU-driven count via an indirect command --
  // the recon handoff. Skip an unbound one; a bound one always draws (its
  // count lives in the producer's command, which this tier cannot inspect).
  void operator()(const LiveMesh& live) const {
    if (live.valid()) {
      live.record_draw(cmd);
    }
  }
};

}  // namespace

core::Result<HybridMeshPipeline> HybridMeshPipeline::create(
    const core::Device& device, core::Allocator& allocator,
    const RenderTargetLayout& layout) {
  VKC_TRY(device.check_enabled(device_requirements())
              .with_context("HybridMeshPipeline::create"));
  const VkDevice vk = device.handle();
  VKC_ASSIGN(ShaderModule vert,
             ShaderModule::create(
                 vk, reinterpret_cast<const uint32_t*>(vg_hybrid_mesh_vert_spv),
                 vg_hybrid_mesh_vert_spv_size));
  VKC_ASSIGN(ShaderModule frag,
             ShaderModule::create(
                 vk, reinterpret_cast<const uint32_t*>(vg_hybrid_mesh_frag_spv),
                 vg_hybrid_mesh_frag_spv_size));

  // Interleaved assets::Vertex input: position (0), normal (1), uv0 (2), and
  // color (3) -- the layout hybrid_mesh.vert declares. tangent is unused by
  // this pipeline, so it is simply not bound.
  const VkVertexInputBindingDescription binding{0, sizeof(assets::Vertex),
                                                VK_VERTEX_INPUT_RATE_VERTEX};
  const VkVertexInputAttributeDescription attrs[4] = {
      {0, 0, VK_FORMAT_R32G32B32_SFLOAT, offsetof(assets::Vertex, position)},
      {1, 0, VK_FORMAT_R32G32B32_SFLOAT, offsetof(assets::Vertex, normal)},
      {2, 0, VK_FORMAT_R32G32_SFLOAT, offsetof(assets::Vertex, uv0)},
      {3, 0, VK_FORMAT_R32G32B32A32_SFLOAT, offsetof(assets::Vertex, color)},
  };

  // The fragment stage writes color attachment 0 only, so its format alone
  // decides the sRGB path.
  const FragmentSpecialization spec_data{
      kHybridMeshLit, kHybridMeshNormals,
      is_srgb_attachment(layout.color_formats[0]) ? VK_TRUE : VK_FALSE,
      kHybridMeshVertexColor};
  const VkSpecializationMapEntry spec_entries[4] = {
      {0, offsetof(FragmentSpecialization, flag_lit), sizeof(uint32_t)},
      {1, offsetof(FragmentSpecialization, flag_normals), sizeof(uint32_t)},
      {2, offsetof(FragmentSpecialization, srgb_target), sizeof(VkBool32)},
      {3, offsetof(FragmentSpecialization, flag_vertex_color),
       sizeof(uint32_t)},
  };
  const VkSpecializationInfo spec{4, spec_entries, sizeof(spec_data),
                                  &spec_data};

  GraphicsPipelineDesc desc;
  desc.vertex_shader = &vert;
  desc.fragment_shader = &frag;
  desc.layout = layout;
  desc.vertex_bindings = &binding;
  desc.vertex_binding_count = 1;
  desc.vertex_attributes = attrs;
  desc.vertex_attribute_count = 4;
  desc.depth_test = true;
  desc.depth_write = true;
  desc.fragment_specialization = &spec;
  VKC_ASSIGN(GraphicsPipeline pipeline, GraphicsPipeline::create(vk, desc));

  // Atlas tiles meet at their edges, so the sampler clamps rather than wraps
  // into the next tile; the atlas has one level.
  SamplerDesc sampler_desc;
  sampler_desc.mipmap_mode = VK_SAMPLER_MIPMAP_MODE_NEAREST;
  sampler_desc.address_mode_u = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
  sampler_desc.address_mode_v = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
  sampler_desc.address_mode_w = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
  sampler_desc.max_lod = 0.0f;
  VKC_ASSIGN(Sampler sampler, Sampler::create(vk, sampler_desc));

  // The fallback is only ever bound with kHybridMeshVertexColor set, so its
  // texel is never shown; it exists so that the shader's sample reads a
  // defined image.
  const uint8_t white[4] = {255, 255, 255, 255};
  ImageUploadDesc fallback_desc;
  fallback_desc.extent = {1, 1};
  fallback_desc.format = VK_FORMAT_R8G8B8A8_UNORM;
  fallback_desc.pixels = white;
  fallback_desc.size = sizeof(white);
  VKC_ASSIGN(core::Image fallback,
             upload_texture(device, allocator, fallback_desc));

  const VkDescriptorPoolSize pool_size{
      VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, 1};
  VKC_ASSIGN(core::DescriptorPool pool,
             core::DescriptorPool::create(vk, &pool_size, 1, 1));
  VKC_ASSIGN(core::DescriptorSet fallback_set,
             pool.allocate(pipeline.descriptor_set_layout(0)));
  fallback_set.write_combined_image_sampler(
      0, fallback.view(), sampler.handle(),
      VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL);

  HybridMeshPipeline hybrid;
  hybrid.device_ = &device;
  hybrid.pipeline_ = std::move(pipeline);
  hybrid.sampler_.emplace(std::move(sampler));
  hybrid.fallback_ = std::move(fallback);
  hybrid.pool_ = std::move(pool);
  hybrid.fallback_set_ = std::move(fallback_set);
  return hybrid;
}

HybridMeshPipeline::HybridMeshPipeline(HybridMeshPipeline&& other) noexcept
    : device_(other.device_),
      pipeline_(std::move(other.pipeline_)),
      sampler_(std::move(other.sampler_)),
      fallback_(std::move(other.fallback_)),
      pool_(std::move(other.pool_)),
      fallback_set_(std::move(other.fallback_set_)) {
  other.device_ = nullptr;
  other.sampler_.reset();
  other.fallback_set_ = {};
}

HybridMeshPipeline& HybridMeshPipeline::operator=(
    HybridMeshPipeline&& other) noexcept {
  if (this != &other) {
    // Release in reverse declaration order -- the set, the pool that frees it,
    // the image it names, the sampler -- before adopting other's.
    fallback_set_ = {};
    pool_ = {};
    fallback_ = {};
    sampler_.reset();
    pipeline_ = {};

    device_ = other.device_;
    pipeline_ = std::move(other.pipeline_);
    sampler_ = std::move(other.sampler_);
    fallback_ = std::move(other.fallback_);
    pool_ = std::move(other.pool_);
    fallback_set_ = std::move(other.fallback_set_);
    other.device_ = nullptr;
    other.sampler_.reset();
    other.fallback_set_ = {};
  }
  return *this;
}

void HybridMeshPipeline::submit(VkCommandBuffer cmd,
                                const HybridMeshFrame& frame) const {
  // A default-constructed or moved-from pipeline has nothing to record.
  if (!valid()) {
    return;
  }

  vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, pipeline_.handle());
  set_full_viewport_scissor(cmd, frame.extent);

  // Set 0 (the atlas combined-image-sampler) binds once for the frame. The
  // fragment shader samples it unconditionally, so a frame without an atlas
  // binds the fallback and draws in vertex color instead.
  const bool has_atlas = frame.atlas != VK_NULL_HANDLE;
  const VkDescriptorSet atlas =
      has_atlas ? frame.atlas : fallback_set_.handle();
  vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS,
                          pipeline_.layout(), 0, 1, &atlas, 0, nullptr);

  // One push for the whole frame: no per-draw model matrix (world-space
  // geometry), so the camera + light are constant across draws. Normalize the
  // light direction once here rather than per fragment; fall back to +Z if the
  // caller passed a zero vector.
  glm::vec3 light_dir = frame.light_dir;
  const float length = glm::length(light_dir);
  light_dir = length > 0.0f ? light_dir / length : glm::vec3(0.0f, 0.0f, 1.0f);

  PushConstants pc;
  pc.view_proj = frame.view_proj;
  pc.light_dir[0] = light_dir.x;
  pc.light_dir[1] = light_dir.y;
  pc.light_dir[2] = light_dir.z;
  pc.flags = has_atlas ? frame.flags : frame.flags | kHybridMeshVertexColor;
  vkCmdPushConstants(cmd, pipeline_.layout(),
                     VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT,
                     0, sizeof(pc), &pc);

  // Each geometry source binds its own vertex/index buffers, so the draws are
  // independent; RecordGeometry decides what a given source records. The
  // push constant above is still worth recording without a draw list, so this
  // guards only the loop.
  if (frame.draws == nullptr) {
    return;
  }
  for (uint32_t i = 0; i < frame.draw_count; ++i) {
    std::visit(RecordGeometry{cmd}, frame.draws[i].geometry);
  }
}

}  // namespace volumetric_kit::gfx::pipelines
