// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Tao Jin

#include "volumetric_kit/gfx/pipelines/hybrid_mesh_pipeline.hpp"

#include <cstddef>
#include <cstdint>
#include <utility>

#include <glm/vec4.hpp>

#include "volumetric_kit/gfx/assets/mesh.hpp"
#include "volumetric_kit/gfx/core/shader.hpp"
#include "volumetric_kit/gfx/pipelines/gpu_mesh.hpp"

// Generated by embed_spirv.cmake from shaders/hybrid_mesh.{vert,frag}: the
// SPIR-V the library ships, as `vg_hybrid_mesh_{vert,frag}_spv` (+ `_size`).
#include "hybrid_mesh_frag.spv.hpp"
#include "hybrid_mesh_vert.spv.hpp"

namespace volumetric_kit::gfx::pipelines {

namespace {

// Per-frame constants for hybrid_mesh.{vert,frag}, shared by both stages. The
// lit flag rides `light.w` (> 0.5 = lit) rather than a trailing `uint`, so the
// block stays a clean 16-byte multiple (80 B) whatever glm's alignment -- a
// trailing scalar could pad the host struct past the reflected push range.
struct PushConstants {
  glm::mat4 view_proj;  // projection * view (vertices are already world-space)
  glm::vec4 light;      // xyz = world-space light direction, w = lit flag
};
static_assert(sizeof(PushConstants) == 80,
              "PushConstants must match the shader push block (mat4 + vec4)");
static_assert(offsetof(PushConstants, light) == 64,
              "PushConstants layout drift");

}  // namespace

Result<HybridMeshPipeline> HybridMeshPipeline::create(
    VkDevice device, const RenderTargetLayout& layout) {
  VG_ASSIGN(
      ShaderModule vert,
      ShaderModule::create(
          device, reinterpret_cast<const uint32_t*>(vg_hybrid_mesh_vert_spv),
          vg_hybrid_mesh_vert_spv_size));
  VG_ASSIGN(
      ShaderModule frag,
      ShaderModule::create(
          device, reinterpret_cast<const uint32_t*>(vg_hybrid_mesh_frag_spv),
          vg_hybrid_mesh_frag_spv_size));

  // Interleaved assets::Vertex input: position (0), normal (1), uv0 (2), and
  // color (3) -- the layout hybrid_mesh.vert declares. tangent is unused by
  // this pipeline, so it is simply not bound.
  const VkVertexInputBindingDescription binding{0, sizeof(assets::Vertex),
                                                VK_VERTEX_INPUT_RATE_VERTEX};
  const VkVertexInputAttributeDescription attrs[4] = {
      {0, 0, VK_FORMAT_R32G32B32_SFLOAT, offsetof(assets::Vertex, position)},
      {1, 0, VK_FORMAT_R32G32B32_SFLOAT, offsetof(assets::Vertex, normal)},
      {2, 0, VK_FORMAT_R32G32_SFLOAT, offsetof(assets::Vertex, uv0)},
      {3, 0, VK_FORMAT_R32G32B32A32_SFLOAT, offsetof(assets::Vertex, color)},
  };

  GraphicsPipelineDesc desc;
  desc.vertex_shader = &vert;
  desc.fragment_shader = &frag;
  desc.layout = layout;
  desc.vertex_bindings = &binding;
  desc.vertex_binding_count = 1;
  desc.vertex_attributes = attrs;
  desc.vertex_attribute_count = 4;
  desc.depth_test = true;
  desc.depth_write = true;
  VG_ASSIGN(GraphicsPipeline pipeline, GraphicsPipeline::create(device, desc));

  HybridMeshPipeline hybrid;
  hybrid.pipeline_ = std::move(pipeline);
  return hybrid;
}

void HybridMeshPipeline::submit(VkCommandBuffer cmd,
                                const HybridMeshFrame& frame) const {
  vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, pipeline_.handle());

  // Full-target viewport + scissor (both dynamic state).
  VkViewport viewport{};
  viewport.width = static_cast<float>(frame.extent.width);
  viewport.height = static_cast<float>(frame.extent.height);
  viewport.minDepth = 0.0f;
  viewport.maxDepth = 1.0f;
  vkCmdSetViewport(cmd, 0, 1, &viewport);
  VkRect2D scissor{};
  scissor.extent = frame.extent;
  vkCmdSetScissor(cmd, 0, 1, &scissor);

  // Set 0 (the atlas combined-image-sampler) binds once for the frame.
  if (frame.atlas != VK_NULL_HANDLE) {
    vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS,
                            pipeline_.layout(), 0, 1, &frame.atlas, 0, nullptr);
  }

  // One push for the whole frame: no per-draw model matrix (world-space
  // geometry), so the camera + light are constant across draws.
  PushConstants pc;
  pc.view_proj = frame.view_proj;
  pc.light = glm::vec4(frame.light_dir,
                       (frame.flags & kHybridMeshLit) != 0u ? 1.0f : 0.0f);
  vkCmdPushConstants(cmd, pipeline_.layout(),
                     VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT,
                     0, sizeof(pc), &pc);

  for (uint32_t i = 0; i < frame.draw_count; ++i) {
    const HybridMeshDraw& draw = frame.draws[i];
    // Skip empty draws so a null/moved-from mesh can't record against a stale
    // binding.
    if (draw.mesh == nullptr || !draw.mesh->valid()) {
      continue;
    }
    draw.mesh->record_draw(cmd);
  }
}

}  // namespace volumetric_kit::gfx::pipelines
