// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Tao Jin

#include "volumetric_kit/gfx/pipelines/image_pipeline.hpp"

#include <algorithm>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <string>
#include <utility>

#include <glm/common.hpp>
#include <glm/vec2.hpp>

#include "volumetric_kit/core/vulkan/allocator.hpp"
#include "volumetric_kit/core/vulkan/buffer.hpp"
#include "volumetric_kit/core/vulkan/device.hpp"
#include "volumetric_kit/core/vulkan/format.hpp"
#include "volumetric_kit/core/vulkan/vk_result.hpp"
#include "volumetric_kit/gfx/core/device_requirements.hpp"
#include "volumetric_kit/gfx/core/image_barrier.hpp"
#include "volumetric_kit/gfx/core/mip_chain.hpp"
#include "volumetric_kit/gfx/core/shader.hpp"
#include "volumetric_kit/gfx/pipelines/impl/pipeline_util.hpp"

// Generated by vkc_embed_shaders from shaders/image_{convert,draw}.{vert,frag}:
// the SPIR-V the library ships, as `vg_image_*_spv` (+ `_size`).
#include "image_convert_frag.spv.hpp"
#include "image_convert_vert.spv.hpp"
#include "image_draw_frag.spv.hpp"
#include "image_draw_vert.spv.hpp"

namespace volumetric_kit::gfx::pipelines {

namespace {

// The display image's format. _SRGB is the point: the convert pass writes
// linear light that the hardware encodes, the mip blits decode, average and
// re-encode, and the draw samples linear light back. Rendering, blitting and
// linear filtering of it are all mandatory in Vulkan.
constexpr VkFormat kDisplayFormat = VK_FORMAT_R8G8B8A8_SRGB;

constexpr VkFormatFeatureFlags kDisplayFeatures =
    VK_FORMAT_FEATURE_SAMPLED_IMAGE_BIT |
    VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_LINEAR_BIT |
    VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BIT | VK_FORMAT_FEATURE_BLIT_SRC_BIT |
    VK_FORMAT_FEATURE_BLIT_DST_BIT;

// image_convert.frag's push block (std430): scalars, then the vec2 at its
// 8-byte alignment. Plain floats rather than glm types, so no glm alignment
// setting can move a member.
struct ConvertPush {
  uint32_t mapping;
  uint32_t srgb_encoded;
  float value_scale;
  float ramp_min;
  float ramp_max;
  uint32_t zero_is_empty;
  float kr;
  float kb;
  uint32_t full_range;
  float chroma_shift_x;
  float chroma_size[2];
};
static_assert(sizeof(ConvertPush) == 48, "ConvertPush must match the shader");
static_assert(offsetof(ConvertPush, chroma_size) == 40,
              "ConvertPush layout drift");

// image_draw.vert's push block (std430): five vec2s.
struct DrawPush {
  float target_size[2];
  float rect_min[2];
  float rect_max[2];
  float uv_min[2];
  float uv_max[2];
};
static_assert(sizeof(DrawPush) == 40, "DrawPush must match the shader");

// The source planes a texture keeps copies of: their formats (_UNORM; the
// encoding is a push constant), how many, whether plane 0's declared format
// is _SRGB, and the factor from a sampled value back to the stored one.
struct PlaneFormats {
  std::array<VkFormat, 2> format{VK_FORMAT_UNDEFINED, VK_FORMAT_UNDEFINED};
  uint32_t count = 1;
  bool srgb_source = false;
  float value_scale = 1.0f;
};

// The 8-bit _SRGB formats' _UNORM twins: same bytes, so a copy between them
// carries the encoded values across unchanged.
VkFormat unorm_twin(VkFormat format) {
  switch (format) {
    case VK_FORMAT_R8_SRGB:
      return VK_FORMAT_R8_UNORM;
    case VK_FORMAT_R8G8_SRGB:
      return VK_FORMAT_R8G8_UNORM;
    case VK_FORMAT_R8G8B8A8_SRGB:
      return VK_FORMAT_R8G8B8A8_UNORM;
    case VK_FORMAT_B8G8R8A8_SRGB:
      return VK_FORMAT_B8G8R8A8_UNORM;
    default:
      return format;
  }
}

core::Result<PlaneFormats> plane_formats(const ImageTextureDesc& desc) {
  PlaneFormats planes;
  switch (desc.mapping) {
    case ImageMapping::Color:
      if (unorm_twin(desc.format) != VK_FORMAT_R8G8B8A8_UNORM &&
          unorm_twin(desc.format) != VK_FORMAT_B8G8R8A8_UNORM) {
        return core::Status::invalid_argument(
            "ImageTexture::create: a Color source is R8G8B8A8 or B8G8R8A8, "
            "_UNORM or _SRGB");
      }
      planes.format[0] = unorm_twin(desc.format);
      planes.srgb_source = desc.format != planes.format[0];
      return planes;
    case ImageMapping::Grey:
    case ImageMapping::Ramp:
      switch (desc.format) {
        case VK_FORMAT_R8_UNORM:
          planes.value_scale = 255.0f;
          break;
        case VK_FORMAT_R16_UNORM:
          planes.value_scale = 65535.0f;
          break;
        case VK_FORMAT_R32_SFLOAT:
          planes.value_scale = 1.0f;
          break;
        default:
          return core::Status::invalid_argument(
              "ImageTexture::create: a Grey or Ramp source is R8_UNORM, "
              "R16_UNORM or R32_SFLOAT");
      }
      planes.format[0] = desc.format;
      return planes;
    case ImageMapping::Nv12:
      planes.format = {VK_FORMAT_R8_UNORM, VK_FORMAT_R8G8_UNORM};
      planes.count = 2;
      return planes;
  }
  return core::Status::invalid_argument(
      "ImageTexture::create: unknown ImageMapping");
}

// Plane `p`'s size: the picture's, or NV12's chroma at half, rounded up.
VkExtent2D plane_extent(VkExtent2D extent, uint32_t p) {
  if (p == 0) {
    return extent;
  }
  return {(extent.width + 1) / 2, (extent.height + 1) / 2};
}

// Checks that `plane` can be copied into a plane of `format` and `extent`.
core::Status check_plane(const ImagePlane& plane, uint32_t p, VkFormat format,
                         VkExtent2D extent) {
  const bool has_image = plane.image != nullptr;
  const bool has_buffer = plane.buffer != nullptr;
  if (has_image == has_buffer) {
    return core::Status::invalid_argument(
        "ImagePipeline::record_update: plane " + std::to_string(p) +
        " must name exactly one of an image and a buffer");
  }
  if (has_image) {
    const core::Image& image = *plane.image;
    if (!image.valid() || image.type() != VK_IMAGE_TYPE_2D ||
        image.samples() != VK_SAMPLE_COUNT_1_BIT) {
      return core::Status::invalid_argument(
          "ImagePipeline::record_update: plane " + std::to_string(p) +
          "'s image is not a single-sample 2D image");
    }
    if ((image.usage() & VK_IMAGE_USAGE_TRANSFER_SRC_BIT) == 0) {
      return core::Status::invalid_argument(
          "ImagePipeline::record_update: plane " + std::to_string(p) +
          "'s image lacks TRANSFER_SRC usage");
    }
    if (image.layout() != VK_IMAGE_LAYOUT_GENERAL &&
        image.layout() != VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL) {
      return core::Status::invalid_argument(
          "ImagePipeline::record_update: plane " + std::to_string(p) +
          "'s image is not in GENERAL or TRANSFER_SRC_OPTIMAL");
    }
    if (unorm_twin(image.format()) != format) {
      return core::Status::invalid_argument(
          "ImagePipeline::record_update: plane " + std::to_string(p) +
          "'s image has the wrong format");
    }
    if (image.width() < extent.width || image.height() < extent.height) {
      return core::Status::invalid_argument(
          "ImagePipeline::record_update: plane " + std::to_string(p) +
          "'s image is smaller than the picture");
    }
    return core::Status{};
  }
  const core::Buffer& buffer = *plane.buffer;
  if (!buffer.valid() ||
      (buffer.usage() & VK_BUFFER_USAGE_TRANSFER_SRC_BIT) == 0) {
    return core::Status::invalid_argument(
        "ImagePipeline::record_update: plane " + std::to_string(p) +
        "'s buffer is empty or lacks TRANSFER_SRC usage");
  }
  const VkDeviceSize texel = core::texel_bytes(format);
  if (plane.offset % texel != 0) {
    return core::Status::invalid_argument(
        "ImagePipeline::record_update: plane " + std::to_string(p) +
        "'s buffer offset is not a multiple of the texel size");
  }
  if (plane.row_length != 0 && plane.row_length < extent.width) {
    return core::Status::invalid_argument(
        "ImagePipeline::record_update: plane " + std::to_string(p) +
        "'s row length is shorter than a row");
  }
  const VkDeviceSize row =
      plane.row_length != 0 ? plane.row_length : extent.width;
  const VkDeviceSize needed =
      plane.offset +
      ((VkDeviceSize{extent.height} - 1) * row + extent.width) * texel;
  if (needed > buffer.size()) {
    return core::Status::invalid_argument(
        "ImagePipeline::record_update: plane " + std::to_string(p) +
        "'s buffer is too small for the picture");
  }
  return core::Status{};
}

core::Result<ShaderModule> embedded_module(VkDevice device,
                                           const unsigned char* spv,
                                           std::size_t size) {
  return ShaderModule::create(device, reinterpret_cast<const uint32_t*>(spv),
                              size);
}

core::Result<Sampler> make_sampler(VkDevice device, VkFilter mag, VkFilter min,
                                   VkSamplerMipmapMode mip, float max_lod) {
  SamplerDesc desc;
  desc.mag_filter = mag;
  desc.min_filter = min;
  desc.mipmap_mode = mip;
  desc.address_mode_u = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
  desc.address_mode_v = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
  desc.address_mode_w = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
  desc.max_lod = max_lod;
  return Sampler::create(device, desc);
}

}  // namespace

// --- ImagePipeline ----------------------------------------------------------

core::Result<ImagePipeline> ImagePipeline::create(
    const core::Device& device, const RenderTargetLayout& layout) {
  VKC_TRY(device.check_enabled(device_requirements())
              .with_context("ImagePipeline::create"));
  if (layout.color_count == 0 ||
      layout.color_formats[0] == VK_FORMAT_UNDEFINED) {
    return core::Status::invalid_argument(
        "ImagePipeline::create: the layout has no color attachment");
  }
  // The draw writes location 0 alone, and a pipeline writes every attachment
  // it declares: further attachments would be left undefined under each image.
  if (layout.color_count > 1) {
    return core::Status::invalid_argument(
        "ImagePipeline::create: the layout has more than one color "
        "attachment");
  }
  if (layout.samples != VK_SAMPLE_COUNT_1_BIT) {
    return core::Status::invalid_argument(
        "ImagePipeline::create: the layout is multisampled");
  }
  if (!device.caps().format_supports(kDisplayFormat, VK_IMAGE_TILING_OPTIMAL,
                                     kDisplayFeatures)) {
    return core::Status::unsupported(
        "ImagePipeline::create: the device cannot render, blit and filter "
        "R8G8B8A8_SRGB");
  }

  const VkDevice vk = device.handle();
  VKC_ASSIGN(ShaderModule convert_vert,
             embedded_module(vk, vg_image_convert_vert_spv,
                             vg_image_convert_vert_spv_size));
  VKC_ASSIGN(ShaderModule convert_frag,
             embedded_module(vk, vg_image_convert_frag_spv,
                             vg_image_convert_frag_spv_size));
  VKC_ASSIGN(
      ShaderModule draw_vert,
      embedded_module(vk, vg_image_draw_vert_spv, vg_image_draw_vert_spv_size));
  VKC_ASSIGN(
      ShaderModule draw_frag,
      embedded_module(vk, vg_image_draw_frag_spv, vg_image_draw_frag_spv_size));

  // The convert pass renders into level 0 of a display image: one fixed
  // layout, whatever the caller's target is.
  GraphicsPipelineDesc convert_desc;
  convert_desc.vertex_shader = &convert_vert;
  convert_desc.fragment_shader = &convert_frag;
  convert_desc.layout.color_formats[0] = kDisplayFormat;
  convert_desc.layout.color_count = 1;
  VKC_ASSIGN(GraphicsPipeline convert,
             GraphicsPipeline::create(vk, convert_desc));

  // The draw renders into the caller's target. Its fragment stage encodes
  // sRGB itself for a _UNORM attachment, which stores what it is given; an
  // _SRGB attachment encodes on write, and a float one holds linear light.
  const VkFormat target_format = layout.color_formats[0];
  const VkBool32 encode_srgb =
      !is_srgb_attachment(target_format) && !is_float_attachment(target_format)
          ? VK_TRUE
          : VK_FALSE;
  const VkSpecializationMapEntry spec_entry{0, 0, sizeof(VkBool32)};
  const VkSpecializationInfo spec{1, &spec_entry, sizeof(encode_srgb),
                                  &encode_srgb};
  GraphicsPipelineDesc draw_desc;
  draw_desc.vertex_shader = &draw_vert;
  draw_desc.fragment_shader = &draw_frag;
  draw_desc.layout = layout;
  draw_desc.fragment_specialization = &spec;
  VKC_ASSIGN(GraphicsPipeline draw, GraphicsPipeline::create(vk, draw_desc));

  // The planes are read texel for texel (texelFetch ignores the filter), and
  // NV12's chroma bilinearly; both single-level. The display is minified
  // through its whole chain and magnified as each draw asks.
  VKC_ASSIGN(Sampler texel,
             make_sampler(vk, VK_FILTER_NEAREST, VK_FILTER_NEAREST,
                          VK_SAMPLER_MIPMAP_MODE_NEAREST, 0.0f));
  VKC_ASSIGN(Sampler chroma,
             make_sampler(vk, VK_FILTER_LINEAR, VK_FILTER_LINEAR,
                          VK_SAMPLER_MIPMAP_MODE_NEAREST, 0.0f));
  VKC_ASSIGN(Sampler nearest,
             make_sampler(vk, VK_FILTER_NEAREST, VK_FILTER_LINEAR,
                          VK_SAMPLER_MIPMAP_MODE_LINEAR, VK_LOD_CLAMP_NONE));
  VKC_ASSIGN(Sampler linear,
             make_sampler(vk, VK_FILTER_LINEAR, VK_FILTER_LINEAR,
                          VK_SAMPLER_MIPMAP_MODE_LINEAR, VK_LOD_CLAMP_NONE));

  ImagePipeline pipeline;
  pipeline.device_ = &device;
  pipeline.convert_ = std::move(convert);
  pipeline.draw_ = std::move(draw);
  pipeline.texel_sampler_.emplace(std::move(texel));
  pipeline.chroma_sampler_.emplace(std::move(chroma));
  pipeline.nearest_sampler_.emplace(std::move(nearest));
  pipeline.linear_sampler_.emplace(std::move(linear));
  return pipeline;
}

ImagePipeline::ImagePipeline(ImagePipeline&& other) noexcept
    : device_(other.device_),
      convert_(std::move(other.convert_)),
      draw_(std::move(other.draw_)),
      texel_sampler_(std::move(other.texel_sampler_)),
      chroma_sampler_(std::move(other.chroma_sampler_)),
      nearest_sampler_(std::move(other.nearest_sampler_)),
      linear_sampler_(std::move(other.linear_sampler_)) {
  other.device_ = nullptr;
  other.texel_sampler_.reset();
  other.chroma_sampler_.reset();
  other.nearest_sampler_.reset();
  other.linear_sampler_.reset();
}

ImagePipeline& ImagePipeline::operator=(ImagePipeline&& other) noexcept {
  if (this != &other) {
    device_ = other.device_;
    convert_ = std::move(other.convert_);
    draw_ = std::move(other.draw_);
    texel_sampler_ = std::move(other.texel_sampler_);
    chroma_sampler_ = std::move(other.chroma_sampler_);
    nearest_sampler_ = std::move(other.nearest_sampler_);
    linear_sampler_ = std::move(other.linear_sampler_);
    other.device_ = nullptr;
    other.texel_sampler_.reset();
    other.chroma_sampler_.reset();
    other.nearest_sampler_.reset();
    other.linear_sampler_.reset();
  }
  return *this;
}

core::Status ImagePipeline::record_update(VkCommandBuffer cmd,
                                          ImageTexture& texture,
                                          const ImageUpdate& update) const {
  if (!valid()) {
    return core::Status::invalid_argument(
        "ImagePipeline::record_update: empty pipeline");
  }
  if (!texture.valid()) {
    return core::Status::invalid_argument(
        "ImagePipeline::record_update: empty texture");
  }
  // The texture was made from these, so they cannot fail here.
  VKC_ASSIGN(const PlaneFormats formats, plane_formats(texture.desc_));
  const VkExtent2D extent = texture.desc_.extent;
  const ImageMapping mapping = texture.desc_.mapping;

  // Validate everything before recording anything, so an error leaves the
  // command buffer and the texture's last picture untouched.
  for (uint32_t p = 0; p < 2; ++p) {
    const ImagePlane& plane = update.planes[p];
    if (p < formats.count) {
      VKC_TRY(
          check_plane(plane, p, formats.format[p], plane_extent(extent, p)));
    } else if (plane.image != nullptr || plane.buffer != nullptr) {
      return core::Status::invalid_argument(
          "ImagePipeline::record_update: plane 1 is for NV12 only");
    }
  }
  if (formats.srgb_source && update.encoding != ImageEncoding::Srgb) {
    return core::Status::invalid_argument(
        "ImagePipeline::record_update: an _SRGB source is sRGB-encoded");
  }
  if (mapping == ImageMapping::Ramp &&
      (!std::isfinite(update.ramp_min) || !std::isfinite(update.ramp_max) ||
       update.ramp_min == update.ramp_max)) {
    return core::Status::invalid_argument(
        "ImagePipeline::record_update: the ramp bounds must be finite and "
        "differ");
  }
  if (mapping == ImageMapping::Nv12 &&
      !(update.kr > 0.0f && update.kb > 0.0f && update.kr + update.kb < 1.0f)) {
    return core::Status::invalid_argument(
        "ImagePipeline::record_update: the matrix weights need kr > 0, "
        "kb > 0 and kr + kb < 1");
  }

  // 1. Copy each source plane into the texture's copy of it. The sources may
  //    have been written by anything earlier on this queue -- a producer's
  //    pass in this or an earlier submission -- so the copies wait for every
  //    earlier write and see its results.
  // TODO: let a plane name its writer's stage and access, to wait for less
  // than all earlier work.
  VkMemoryBarrier written{};
  written.sType = VK_STRUCTURE_TYPE_MEMORY_BARRIER;
  written.srcAccessMask = VK_ACCESS_MEMORY_WRITE_BIT;
  written.dstAccessMask = VK_ACCESS_TRANSFER_READ_BIT;
  vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_ALL_COMMANDS_BIT,
                       VK_PIPELINE_STAGE_TRANSFER_BIT, 0, 1, &written, 0,
                       nullptr, 0, nullptr);

  // The plane copies' previous contents are discarded, but the previous
  // update's convert pass may still be reading them: wait for its fragment
  // stage.
  std::array<ImageBarrierDesc, 2> to_copy{};
  std::array<ImageBarrierDesc, 2> to_read{};
  for (uint32_t p = 0; p < formats.count; ++p) {
    to_copy[p].image = texture.planes_[p].handle();
    to_copy[p].src_stage = VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT;
    to_copy[p].dst_stage = VK_PIPELINE_STAGE_TRANSFER_BIT;
    to_copy[p].dst_access = VK_ACCESS_TRANSFER_WRITE_BIT;
    to_copy[p].old_layout = VK_IMAGE_LAYOUT_UNDEFINED;
    to_copy[p].new_layout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;

    to_read[p].image = texture.planes_[p].handle();
    to_read[p].src_stage = VK_PIPELINE_STAGE_TRANSFER_BIT;
    to_read[p].dst_stage = VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT;
    to_read[p].src_access = VK_ACCESS_TRANSFER_WRITE_BIT;
    to_read[p].dst_access = VK_ACCESS_SHADER_READ_BIT;
    to_read[p].old_layout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;
    to_read[p].new_layout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;
  }
  cmd_image_barriers(cmd, to_copy.data(), formats.count);

  for (uint32_t p = 0; p < formats.count; ++p) {
    const ImagePlane& plane = update.planes[p];
    const VkImage dst = texture.planes_[p].handle();
    const VkExtent2D size = plane_extent(extent, p);
    if (plane.image != nullptr) {
      VkImageCopy region{};
      region.srcSubresource = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, 1};
      region.dstSubresource = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, 1};
      region.extent = {size.width, size.height, 1};
      vkCmdCopyImage(cmd, plane.image->handle(), plane.image->layout(), dst,
                     VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, 1, &region);
    } else {
      VkBufferImageCopy region{};
      region.bufferOffset = plane.offset;
      region.bufferRowLength = plane.row_length;
      region.imageSubresource = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, 1};
      region.imageExtent = {size.width, size.height, 1};
      vkCmdCopyBufferToImage(cmd, plane.buffer->handle(), dst,
                             VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, 1, &region);
    }
  }
  cmd_image_barriers(cmd, to_read.data(), formats.count);

  // And every later command on the queue waits for the copies, so a producer
  // may write the next picture into a source without a barrier of its own: an
  // execution dependency settles write-after-read.
  vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_TRANSFER_BIT,
                       VK_PIPELINE_STAGE_ALL_COMMANDS_BIT, 0, 0, nullptr, 0,
                       nullptr, 0, nullptr);

  // 2. Convert into level 0 of the display image. Its old contents are
  //    discarded; earlier draws sampling it and the earlier chain's blits
  //    reading it must finish first.
  ImageBarrierDesc to_attachment;
  to_attachment.image = texture.display_.handle();
  to_attachment.src_stage =
      VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT | VK_PIPELINE_STAGE_TRANSFER_BIT;
  to_attachment.dst_stage = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
  to_attachment.dst_access = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
  to_attachment.old_layout = VK_IMAGE_LAYOUT_UNDEFINED;
  to_attachment.new_layout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;
  to_attachment.base_mip = 0;
  to_attachment.mip_count = 1;
  cmd_image_barrier(cmd, to_attachment);

  const RenderTargetAttachment attachment{
      texture.display_.handle(), texture.level0_view_.get(), kDisplayFormat};
  const RenderTarget level0(extent, &attachment, 1, VK_SAMPLE_COUNT_1_BIT);
  RenderTargetBeginInfo begin;
  begin.load_op = VK_ATTACHMENT_LOAD_OP_DONT_CARE;  // every texel is written
  level0.begin(cmd, begin);

  vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, convert_.handle());
  set_full_viewport_scissor(cmd, extent);
  const VkDescriptorSet convert_set = texture.convert_set_.handle();
  vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS,
                          convert_.layout(), 0, 1, &convert_set, 0, nullptr);

  const VkExtent2D chroma = plane_extent(extent, 1);
  ConvertPush push{};
  push.mapping = static_cast<uint32_t>(mapping);
  push.srgb_encoded = update.encoding == ImageEncoding::Srgb ? 1u : 0u;
  push.value_scale = formats.value_scale;
  push.ramp_min = update.ramp_min;
  push.ramp_max = update.ramp_max;
  push.zero_is_empty = update.zero_is_empty ? 1u : 0u;
  push.kr = update.kr;
  push.kb = update.kb;
  push.full_range = update.full_range ? 1u : 0u;
  push.chroma_shift_x =
      update.chroma_siting == ChromaSiting::Left ? 0.25f : 0.0f;
  push.chroma_size[0] = static_cast<float>(chroma.width);
  push.chroma_size[1] = static_cast<float>(chroma.height);
  vkCmdPushConstants(cmd, convert_.layout(), VK_SHADER_STAGE_FRAGMENT_BIT, 0,
                     sizeof(push), &push);
  vkCmdDraw(cmd, 3, 1, 0, 0);
  level0.end(cmd);

  // 3. Build the chain from level 0. The levels below were sampled by earlier
  //    draws, which the blits that overwrite them wait for.
  MipChainDesc mips;
  mips.image = texture.display_.handle();
  mips.extent = extent;
  mips.mip_levels = texture.display_.mip_levels();
  mips.base_layout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;
  mips.base_stage = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
  mips.base_access = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
  mips.upper_layout = VK_IMAGE_LAYOUT_UNDEFINED;
  mips.upper_read_stages = VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT;
  mips.dst_stages = VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT;
  cmd_generate_mips(cmd, mips);

  for (uint32_t p = 0; p < formats.count; ++p) {
    texture.planes_[p].set_layout(VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL);
  }
  texture.display_.set_layout(VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL);
  texture.has_picture_ = true;
  return core::Status{};
}

void ImagePipeline::submit(VkCommandBuffer cmd, const ImageFrame& frame) const {
  if (!valid() || frame.draws == nullptr || frame.draw_count == 0 ||
      frame.extent.width == 0 || frame.extent.height == 0) {
    return;
  }

  vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, draw_.handle());
  set_full_viewport_scissor(cmd, frame.extent);

  const glm::vec2 target{static_cast<float>(frame.extent.width),
                         static_cast<float>(frame.extent.height)};
  for (uint32_t i = 0; i < frame.draw_count; ++i) {
    const ImageDraw& draw = frame.draws[i];
    const ImageTexture* texture = draw.texture;
    if (texture == nullptr || !texture->valid() || !texture->has_picture_ ||
        !(draw.scale > 0.0f) || !std::isfinite(draw.scale)) {
      continue;
    }

    // The image's rectangle in target pixels, clipped to the viewport and the
    // target, and the part of the image that remains. Clipping on the host
    // keeps the rectangle within the target however far the view zooms, and
    // leaves the texture coordinates' screen derivatives -- which pick the
    // mip level -- exactly those of the whole image.
    const glm::vec2 size{
        static_cast<float>(texture->desc_.extent.width) * draw.scale,
        static_cast<float>(texture->desc_.extent.height) * draw.scale};
    const glm::vec2 viewport_min{static_cast<float>(draw.viewport.offset.x),
                                 static_cast<float>(draw.viewport.offset.y)};
    const glm::vec2 viewport_max =
        viewport_min +
        glm::vec2{static_cast<float>(draw.viewport.extent.width),
                  static_cast<float>(draw.viewport.extent.height)};
    const glm::vec2 lo =
        glm::max(glm::max(draw.origin, viewport_min), glm::vec2{0.0f, 0.0f});
    const glm::vec2 hi =
        glm::min(glm::min(draw.origin + size, viewport_max), target);
    if (!(hi.x > lo.x && hi.y > lo.y)) {
      continue;
    }
    const glm::vec2 uv_lo = (lo - draw.origin) / size;
    const glm::vec2 uv_hi = (hi - draw.origin) / size;

    const VkDescriptorSet set =
        texture->draw_sets_[draw.magnify == ImageFilter::Linear ? 1 : 0]
            .handle();
    vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS,
                            draw_.layout(), 0, 1, &set, 0, nullptr);
    const DrawPush push{{target.x, target.y},
                        {lo.x, lo.y},
                        {hi.x, hi.y},
                        {uv_lo.x, uv_lo.y},
                        {uv_hi.x, uv_hi.y}};
    vkCmdPushConstants(cmd, draw_.layout(), VK_SHADER_STAGE_VERTEX_BIT, 0,
                       sizeof(push), &push);
    vkCmdDraw(cmd, 6, 1, 0, 0);
  }
}

// --- ImageTexture -----------------------------------------------------------

core::Result<ImageTexture> ImageTexture::create(const ImagePipeline& pipeline,
                                                core::Allocator& allocator,
                                                const ImageTextureDesc& desc) {
  if (!pipeline.valid()) {
    return core::Status::invalid_argument(
        "ImageTexture::create: empty pipeline");
  }
  const core::Device& device = *pipeline.device_;
  if (desc.extent.width == 0 || desc.extent.height == 0) {
    return core::Status::invalid_argument("ImageTexture::create: zero extent");
  }
  // The convert pass renders level 0 whole, so the extent must fit a
  // framebuffer and a viewport as well as an image.
  const VkPhysicalDeviceLimits& limits = device.caps().limits();
  const uint32_t max_width =
      std::min({limits.maxImageDimension2D, limits.maxFramebufferWidth,
                limits.maxViewportDimensions[0]});
  const uint32_t max_height =
      std::min({limits.maxImageDimension2D, limits.maxFramebufferHeight,
                limits.maxViewportDimensions[1]});
  if (desc.extent.width > max_width || desc.extent.height > max_height) {
    return core::Status::invalid_argument(
        "ImageTexture::create: extent beyond the device's image, framebuffer "
        "or viewport limits");
  }
  VKC_ASSIGN(const PlaneFormats formats, plane_formats(desc));

  ImageTexture texture;
  texture.desc_ = desc;
  for (uint32_t p = 0; p < formats.count; ++p) {
    VkFormatFeatureFlags features = VK_FORMAT_FEATURE_SAMPLED_IMAGE_BIT |
                                    VK_FORMAT_FEATURE_TRANSFER_DST_BIT;
    if (p == 1) {
      features |= VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_LINEAR_BIT;
    }
    if (!device.caps().format_supports(formats.format[p],
                                       VK_IMAGE_TILING_OPTIMAL, features)) {
      return core::Status::unsupported(
          "ImageTexture::create: the device cannot sample or copy into "
          "plane " +
          std::to_string(p) + "'s format");
    }
    core::ImageDesc plane_desc;
    plane_desc.extent = plane_extent(desc.extent, p);
    plane_desc.format = formats.format[p];
    plane_desc.usage =
        VK_IMAGE_USAGE_TRANSFER_DST_BIT | VK_IMAGE_USAGE_SAMPLED_BIT;
    VKC_ASSIGN(texture.planes_[p], allocator.create_image(plane_desc));
  }

  core::ImageDesc display_desc;
  display_desc.extent = desc.extent;
  display_desc.format = kDisplayFormat;
  display_desc.mip_levels = mip_level_count(desc.extent);
  display_desc.usage =
      VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT | VK_IMAGE_USAGE_SAMPLED_BIT |
      VK_IMAGE_USAGE_TRANSFER_SRC_BIT | VK_IMAGE_USAGE_TRANSFER_DST_BIT;
  VKC_ASSIGN(texture.display_, allocator.create_image(display_desc));

  const VkDevice vk = device.handle();
  VkImageViewCreateInfo view_info{};
  view_info.sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO;
  view_info.image = texture.display_.handle();
  view_info.viewType = VK_IMAGE_VIEW_TYPE_2D;
  view_info.format = kDisplayFormat;
  view_info.subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1};
  VkImageView level0 = VK_NULL_HANDLE;
  VKC_VK_TRY(vkCreateImageView(vk, &view_info, nullptr, &level0));
  texture.level0_view_ =
      core::UniqueHandle<VkImageView, vkDestroyImageView>(vk, level0);

  // One convert set (the planes) and two draw sets (the display, magnified
  // nearest and linear): four combined image samplers in all.
  const VkDescriptorPoolSize pool_size{
      VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, 4};
  VKC_ASSIGN(texture.pool_, core::DescriptorPool::create(vk, &pool_size, 1, 3));
  VKC_ASSIGN(
      texture.convert_set_,
      texture.pool_.allocate(pipeline.convert_.descriptor_set_layout(0)));
  // Binding 1 is NV12's chroma, filtered. Other sources bind plane 0 again,
  // as every binding the shader declares must hold a descriptor -- with the
  // nearest sampler, since their formats need not support linear filtering
  // and the shader's (unreached) sample of binding 1 still counts as a use.
  const bool nv12 = formats.count > 1;
  texture.convert_set_.write_combined_image_sampler(
      0, texture.planes_[0].view(), pipeline.texel_sampler_->handle(),
      VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL);
  texture.convert_set_.write_combined_image_sampler(
      1, texture.planes_[nv12 ? 1 : 0].view(),
      (nv12 ? pipeline.chroma_sampler_ : pipeline.texel_sampler_)->handle(),
      VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL);

  const VkSampler draw_samplers[2] = {pipeline.nearest_sampler_->handle(),
                                      pipeline.linear_sampler_->handle()};
  for (uint32_t i = 0; i < 2; ++i) {
    VKC_ASSIGN(texture.draw_sets_[i],
               texture.pool_.allocate(pipeline.draw_.descriptor_set_layout(0)));
    texture.draw_sets_[i].write_combined_image_sampler(
        0, texture.display_.view(), draw_samplers[i],
        VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL);
  }
  return texture;
}

ImageTexture::ImageTexture(ImageTexture&& other) noexcept
    : desc_(other.desc_),
      planes_(std::move(other.planes_)),
      display_(std::move(other.display_)),
      level0_view_(std::move(other.level0_view_)),
      pool_(std::move(other.pool_)),
      convert_set_(other.convert_set_),
      draw_sets_(other.draw_sets_),
      has_picture_(other.has_picture_) {
  other.desc_ = {};
  other.convert_set_ = {};
  other.draw_sets_ = {};
  other.has_picture_ = false;
}

ImageTexture& ImageTexture::operator=(ImageTexture&& other) noexcept {
  if (this != &other) {
    // Release in reverse declaration order -- the sets, the pool that frees
    // them, the view, then the images it views -- before adopting other's.
    convert_set_ = {};
    draw_sets_ = {};
    pool_ = {};
    level0_view_ = {};
    display_ = {};
    planes_ = {};

    desc_ = other.desc_;
    planes_ = std::move(other.planes_);
    display_ = std::move(other.display_);
    level0_view_ = std::move(other.level0_view_);
    pool_ = std::move(other.pool_);
    convert_set_ = other.convert_set_;
    draw_sets_ = other.draw_sets_;
    has_picture_ = other.has_picture_;

    other.desc_ = {};
    other.convert_set_ = {};
    other.draw_sets_ = {};
    other.has_picture_ = false;
  }
  return *this;
}

}  // namespace volumetric_kit::gfx::pipelines
