// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Tao Jin

#include "volumetric_kit/gfx/pipelines/patch_mesh_pipeline.hpp"

#include <cstddef>
#include <cstdint>
#include <utility>
#include <variant>

#include <glm/geometric.hpp>
#include <glm/vec3.hpp>
#include <glm/vec4.hpp>

#include "volumetric_kit/gfx/assets/mesh.hpp"
#include "volumetric_kit/gfx/core/shader.hpp"
#include "volumetric_kit/gfx/pipelines/gpu_mesh.hpp"
#include "volumetric_kit/gfx/pipelines/impl/pipeline_util.hpp"
#include "volumetric_kit/gfx/pipelines/live_mesh.hpp"

// Generated by embed_spirv.cmake from shaders/patch_mesh.{vert,frag}.
#include "patch_mesh_frag.spv.hpp"
#include "patch_mesh_vert.spv.hpp"

namespace volumetric_kit::gfx::pipelines {

namespace {

// Per-frame constants for patch_mesh.{vert,frag}, shared by both stages. The
// lit flag rides `light.w` and the patch shape rides a `uvec4` rather than two
// trailing scalars, so the block stays a clean 16-byte multiple (96 B) whatever
// glm's alignment -- a trailing scalar pair could pad the host struct past the
// reflected push range.
struct PushConstants {
  glm::mat4 view_proj;  // projection * view (vertices are already world-space)
  glm::vec4 light;      // xyz = world-space light direction, w = lit flag
  glm::uvec4
      patch_shape;  // x = texels per leg, y = texels per patch, zw unused
};
static_assert(sizeof(PushConstants) == 96,
              "PushConstants must match the shader push block");
static_assert(offsetof(PushConstants, light) == 64, "PushConstants drift");
static_assert(offsetof(PushConstants, patch_shape) == 80,
              "PushConstants drift");

// The vertex ABI, pinned for the reason hybrid_mesh_pipeline.cpp pins it -- a
// LiveMesh's vertices are written by a separate library against these exact
// bytes. This pipeline depends on the layout TWICE over: once through the
// vertex-input attributes below, and once through the fragment stage, which
// reads positions out of the same buffer as a flat float array at
// `v * 16 + 0..2`. So a change here is a wire break in the shader as well, and
// in a place no vertex-input description would catch.
static_assert(sizeof(assets::Vertex) == 64, "assets::Vertex stride drift");
static_assert(sizeof(assets::Vertex) == 16 * sizeof(float),
              "patch_mesh.frag reads 16 floats per vertex");
static_assert(offsetof(assets::Vertex, position) == 0, "vertex layout drift");
static_assert(offsetof(assets::Vertex, normal) == 12, "vertex layout drift");
static_assert(offsetof(assets::Vertex, tangent) == 24, "vertex layout drift");
static_assert(offsetof(assets::Vertex, uv0) == 40, "vertex layout drift");
static_assert(offsetof(assets::Vertex, color) == 48, "vertex layout drift");

// The fragment stage divides by `patch_leg - 1` to turn a barycentric
// coordinate into a texel, so one texel per leg has no span to divide across.
constexpr std::uint32_t kMinPatchLeg = 2;

// Records one draw's geometry. A visitor rather than a get_if chain: std::visit
// requires every alternative to be handled, so adding a geometry source to
// PatchMeshDraw is a compile error here instead of a draw that silently records
// nothing.
struct RecordGeometry {
  VkCommandBuffer cmd;

  void operator()(const GpuMesh* mesh) const {
    if (mesh != nullptr && mesh->valid()) {
      mesh->record_draw(cmd);
    }
  }

  void operator()(const LiveMesh& live) const {
    if (live.valid()) {
      live.record_draw(cmd);
    }
  }
};

}  // namespace

Result<PatchMeshPipeline> PatchMeshPipeline::create(
    VkDevice device, const RenderTargetLayout& layout) {
  VG_ASSIGN(
      ShaderModule vert,
      ShaderModule::create(
          device, reinterpret_cast<const uint32_t*>(vg_patch_mesh_vert_spv),
          vg_patch_mesh_vert_spv_size));
  VG_ASSIGN(
      ShaderModule frag,
      ShaderModule::create(
          device, reinterpret_cast<const uint32_t*>(vg_patch_mesh_frag_spv),
          vg_patch_mesh_frag_spv_size));

  // Interleaved assets::Vertex input: position (0), normal (1), color (2).
  // uv0 is NOT bound -- this pipeline's whole premise is that a per-vertex
  // texture coordinate cannot address a per-triangle patch, so the slot is
  // simply not read. tangent is unused, as in the hybrid pipeline.
  const VkVertexInputBindingDescription binding{0, sizeof(assets::Vertex),
                                                VK_VERTEX_INPUT_RATE_VERTEX};
  const VkVertexInputAttributeDescription attrs[3] = {
      {0, 0, VK_FORMAT_R32G32B32_SFLOAT, offsetof(assets::Vertex, position)},
      {1, 0, VK_FORMAT_R32G32B32_SFLOAT, offsetof(assets::Vertex, normal)},
      {2, 0, VK_FORMAT_R32G32B32A32_SFLOAT, offsetof(assets::Vertex, color)},
  };

  GraphicsPipelineDesc desc;
  desc.vertex_shader = &vert;
  desc.fragment_shader = &frag;
  desc.layout = layout;
  desc.vertex_bindings = &binding;
  desc.vertex_binding_count = 1;
  desc.vertex_attributes = attrs;
  desc.vertex_attribute_count = 3;
  desc.depth_test = true;
  desc.depth_write = true;
  VG_ASSIGN(GraphicsPipeline pipeline, GraphicsPipeline::create(device, desc));

  PatchMeshPipeline patch;
  patch.pipeline_ = std::move(pipeline);
  return patch;
}

void PatchMeshPipeline::submit(VkCommandBuffer cmd,
                               const PatchMeshFrame& frame) const {
  // The fragment shader statically reads all three buffers of set 0, so a valid
  // set must be bound for any draw to be legal. And the patch shape is what
  // turns a barycentric coordinate into a texel index: a zero leg would divide
  // by minus one and address the atlas anywhere, which is worse than drawing
  // nothing. Both are dropped rather than recorded.
  if (!valid() || frame.atlas == VK_NULL_HANDLE ||
      frame.patch_leg < kMinPatchLeg || frame.texels_per_patch == 0) {
    return;
  }

  vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, pipeline_.handle());
  set_full_viewport_scissor(cmd, frame.extent);

  // Set 0 binds once for the frame: every draw in it reads the same producer's
  // atlas, index run and vertices.
  vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS,
                          pipeline_.layout(), 0, 1, &frame.atlas, 0, nullptr);

  glm::vec3 light_dir = frame.light_dir;
  const float length = glm::length(light_dir);
  light_dir = length > 0.0f ? light_dir / length : glm::vec3(0.0f, 0.0f, 1.0f);

  PushConstants pc;
  pc.view_proj = frame.view_proj;
  pc.light =
      glm::vec4(light_dir, (frame.flags & kPatchMeshLit) != 0u ? 1.0f : 0.0f);
  pc.patch_shape = glm::uvec4(frame.patch_leg, frame.texels_per_patch, 0u, 0u);
  vkCmdPushConstants(cmd, pipeline_.layout(),
                     VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT,
                     0, sizeof(pc), &pc);

  if (frame.draws == nullptr) {
    return;
  }
  for (std::uint32_t i = 0; i < frame.draw_count; ++i) {
    std::visit(RecordGeometry{cmd}, frame.draws[i].geometry);
  }
}

}  // namespace volumetric_kit::gfx::pipelines
