// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Tao Jin

#include "volumetric_kit/gfx/pipelines/pbr_pipeline.hpp"

#include <cstddef>
#include <cstdint>
#include <utility>

#include "volumetric_kit/gfx/assets/mesh.hpp"
#include "volumetric_kit/gfx/core/shader.hpp"
#include "volumetric_kit/gfx/pipelines/gpu_mesh.hpp"
#include "volumetric_kit/gfx/pipelines/impl/pipeline_util.hpp"
#include "volumetric_kit/gfx/pipelines/pbr_material.hpp"
#include "volumetric_kit/gfx/pipelines/pbr_scene.hpp"

// Generated by embed_spirv.cmake from shaders/model.{vert,frag}: the SPIR-V the
// library ships, as `vg_model_{vert,frag}_spv` (+ `_size`).
#include "model_frag.spv.hpp"
#include "model_vert.spv.hpp"

namespace volumetric_kit::gfx::pipelines {

namespace {

// Per-draw transform fed to model.vert as a push constant (128 bytes -- the
// guaranteed minimum maxPushConstantsSize). Layout matches the shader's block.
struct PushConstants {
  glm::mat4 mvp;    // projection * view * world
  glm::mat4 model;  // world (for the world-space normal)
};

}  // namespace

Result<PbrPipeline> PbrPipeline::create(VkDevice device,
                                        const RenderTargetLayout& layout) {
  VG_ASSIGN(ShaderModule vert,
            ShaderModule::create(
                device, reinterpret_cast<const uint32_t*>(vg_model_vert_spv),
                vg_model_vert_spv_size));
  VG_ASSIGN(ShaderModule frag,
            ShaderModule::create(
                device, reinterpret_cast<const uint32_t*>(vg_model_frag_spv),
                vg_model_frag_spv_size));

  // Interleaved assets::Vertex input: position (0), normal (1), uv0 (2), and
  // tangent (3) -- the layout model.vert declares.
  const VkVertexInputBindingDescription binding{0, sizeof(assets::Vertex),
                                                VK_VERTEX_INPUT_RATE_VERTEX};
  const VkVertexInputAttributeDescription attrs[4] = {
      {0, 0, VK_FORMAT_R32G32B32_SFLOAT, offsetof(assets::Vertex, position)},
      {1, 0, VK_FORMAT_R32G32B32_SFLOAT, offsetof(assets::Vertex, normal)},
      {2, 0, VK_FORMAT_R32G32_SFLOAT, offsetof(assets::Vertex, uv0)},
      {3, 0, VK_FORMAT_R32G32B32A32_SFLOAT, offsetof(assets::Vertex, tangent)},
  };

  GraphicsPipelineDesc desc;
  desc.vertex_shader = &vert;
  desc.fragment_shader = &frag;
  desc.layout = layout;
  desc.vertex_bindings = &binding;
  desc.vertex_binding_count = 1;
  desc.vertex_attributes = attrs;
  desc.vertex_attribute_count = 4;
  desc.depth_test = true;
  desc.depth_write = true;
  VG_ASSIGN(GraphicsPipeline pipeline, GraphicsPipeline::create(device, desc));

  PbrPipeline pbr;
  pbr.pipeline_ = std::move(pipeline);
  return pbr;
}

void PbrPipeline::submit(VkCommandBuffer cmd, const PbrFrame& frame) const {
  // model.frag reads set 0 (camera position + the three IBL maps) in main()
  // with no branch, so a *valid* scene set must be bound for any draw to be
  // legal. Drop the whole frame when there is none rather than recording draws
  // against an unbound or VK_NULL_HANDLE set -- matching HybridMeshPipeline's
  // missing-atlas handling above. Three ways to get here:
  //   - no pipeline (default-constructed or moved-from);
  //   - no scene at all;
  //   - a slot past the scene's UBO ring. PbrScene::create defaults
  //     frames_in_flight to 1 while FrameLoop::create and WindowedAppConfig
  //     default to 2, so the documented `pbr_frame.slot = f.slot` wiring hands
  //     us slot 1 on alternate frames unless the scene was sized to match.
  if (!valid() || frame.scene == nullptr ||
      frame.slot >= frame.scene->frames_in_flight()) {
    return;
  }
  const VkDescriptorSet scene = frame.scene->descriptor_set(frame.slot);
  if (scene == VK_NULL_HANDLE) {
    return;
  }

  vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, pipeline_.handle());
  set_full_viewport_scissor(cmd, frame.extent);

  // Set 0 (scene: camera + IBL) binds once for every draw, selecting the
  // frame's in-flight slot from the scene's UBO ring.
  vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS,
                          pipeline_.layout(), 0, 1, &scene, 0, nullptr);

  if (frame.draws == nullptr) {
    return;
  }

  // Set 1 is rebound only when the material changes from the previous draw, so
  // a run of same-material meshes binds it once.
  VkDescriptorSet bound_material = VK_NULL_HANDLE;
  for (uint32_t i = 0; i < frame.draw_count; ++i) {
    const PbrDraw& draw = frame.draws[i];
    // Skip draws with no geometry or no material: set 1 must be bound for the
    // mesh to shade, so a material-less draw is dropped rather than drawn
    // against a stale binding.
    if (draw.mesh == nullptr || !draw.mesh->valid() ||
        draw.material == nullptr) {
      continue;
    }
    PushConstants pc;
    pc.mvp = frame.view_proj * draw.world;
    pc.model = draw.world;
    vkCmdPushConstants(cmd, pipeline_.layout(), VK_SHADER_STAGE_VERTEX_BIT, 0,
                       sizeof(pc), &pc);
    // Set 1 (this draw's material: factor UBO + the five maps).
    const VkDescriptorSet material = draw.material->descriptor_set();
    if (material != bound_material) {
      vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS,
                              pipeline_.layout(), 1, 1, &material, 0, nullptr);
      bound_material = material;
    }
    draw.mesh->record_draw(cmd);
  }
}

}  // namespace volumetric_kit::gfx::pipelines
