// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Tao Jin

#include "volumetric_kit/gfx/pipelines/pbr_pipeline.hpp"

#include <cstddef>
#include <cstdint>
#include <utility>

#include "volumetric_kit/gfx/assets/mesh.hpp"
#include "volumetric_kit/gfx/core/shader.hpp"

// Generated by embed_spirv.cmake from shaders/model.{vert,frag}: the SPIR-V the
// library ships, as `vg_model_{vert,frag}_spv` (+ `_size`).
#include "model_frag.spv.hpp"
#include "model_vert.spv.hpp"

namespace volumetric_kit::gfx::pipelines {

Result<PbrPipeline> PbrPipeline::create(VkDevice device,
                                        const RenderTargetLayout& layout) {
  VG_ASSIGN(ShaderModule vert,
            ShaderModule::create(
                device, reinterpret_cast<const uint32_t*>(vg_model_vert_spv),
                vg_model_vert_spv_size));
  VG_ASSIGN(ShaderModule frag,
            ShaderModule::create(
                device, reinterpret_cast<const uint32_t*>(vg_model_frag_spv),
                vg_model_frag_spv_size));

  // Interleaved assets::Vertex input: position (0), normal (1), uv0 (2), and
  // tangent (3) -- the layout model.vert declares.
  const VkVertexInputBindingDescription binding{0, sizeof(assets::Vertex),
                                                VK_VERTEX_INPUT_RATE_VERTEX};
  const VkVertexInputAttributeDescription attrs[4] = {
      {0, 0, VK_FORMAT_R32G32B32_SFLOAT, offsetof(assets::Vertex, position)},
      {1, 0, VK_FORMAT_R32G32B32_SFLOAT, offsetof(assets::Vertex, normal)},
      {2, 0, VK_FORMAT_R32G32_SFLOAT, offsetof(assets::Vertex, uv0)},
      {3, 0, VK_FORMAT_R32G32B32A32_SFLOAT, offsetof(assets::Vertex, tangent)},
  };

  GraphicsPipelineDesc desc;
  desc.vertex_shader = &vert;
  desc.fragment_shader = &frag;
  desc.layout = layout;
  desc.vertex_bindings = &binding;
  desc.vertex_binding_count = 1;
  desc.vertex_attributes = attrs;
  desc.vertex_attribute_count = 4;
  desc.depth_test = true;
  desc.depth_write = true;
  VG_ASSIGN(GraphicsPipeline pipeline, GraphicsPipeline::create(device, desc));

  PbrPipeline pbr;
  pbr.pipeline_ = std::move(pipeline);
  return pbr;
}

}  // namespace volumetric_kit::gfx::pipelines
