name: ubuntu-22.04

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ubuntu-22.04
    uses: ./.github/workflows/_build.yml
    with:
      os: ubuntu-22.04
