name: macos-26

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: macos-26
    uses: ./.github/workflows/_build.yml
    with:
      os: macos-26
